name: Report on Push

on:
  push:
    branches: [ main ]

jobs:
  check-status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get previous job status
        run: echo "::set-output name=job_status::${{ job.status }}"

  report:
    runs-on: ubuntu-latest
    needs: check-status  # This job depends on the previous one
    steps:
      - uses: actions/checkout@v3

      - name: Get previous job status
        uses: actions/github-script@v6  # Use a dedicated script action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            core.setOutput('job_status', github.workflows['check-status'].jobs['check-status'].steps[0].outputs.job_status);

      - name: Send deployment report
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          JOB_STATUS: ${{ steps.get-status.outputs.job_status }}
        run: |
          node index.js  # Replace with your compiled script path
          $DISCORD_WEBHOOK_URL
          $(( $JOB_STATUS == 'success' ? 0x33cc33 : 0xcccc00 ))  # Green for success, red for failure
          "Deployment for commit ${{ github.sha }} - $JOB_STATUS"
