name: Report with Local Build Duration

on:
  push:
    branches: [ main ]

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install 

      - name: Install Axios
        run: yarn add axios

      - name: Compile TypeScript (if applicable)
        # Only run compilation if you have TypeScript code
        run: yarn run build || true

      - name: Build your site
        run: |
          BUILD_START_TIME=$(date +%s)
          BUILD_END_TIME=$(date +%s)
          BUILD_DURATION=$((BUILD_END_TIME - BUILD_START_TIME))
          echo "::set-output name=build_duration::$BUILD_DURATION"

      - name: Send deployment report
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          SUCCESS: ${{ true }}
        run: |
          node js/index.js  # Replace with your compiled script path
          $DISCORD_WEBHOOK_URL
          $(( $SUCCESS ? 0x33cc33 : 0xcccc00 ))  # Green for success, red for failure
          "Build for push ${{ github.sha }} ${( $SUCCESS ? 'Successful!' : 'Failed!' )}. Build duration: ${{ steps.build_duration.outputs.build_duration }} seconds"
