name: Report on Push

on:
  push:
    branches: [ main ]

jobs:
  check-status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get previous job status
        run: echo "::set-output name=job_status::${{ job.status }}"

  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get previous job status (if available)
        uses: actions/github-script@v6  # Use a dedicated script action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            let jobStatus = '';
            if (github.workflows['check-status'] && github.workflows['check-status'].jobs['check-status']) {
              jobStatus = github.workflows['check-status'].jobs['check-status'].steps[0].outputs.job_status;
            }
            core.setOutput('job_status', jobStatus);

      - name: Send deployment report
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          JOB_STATUS: ${{ steps.get-status.outputs.job_status }}
        run: |
          # Handle the case where job_status might be undefined
          if [[ -z "$JOB_STATUS" ]]; then
            echo "Previous job status unavailable. Skipping report."
            exit 0
          fi
          node index.js  # Replace with your compiled script path
          $DISCORD_WEBHOOK_URL
          $(( $JOB_STATUS == 'success' ? 0x33cc33 : 0xcccc00 ))  # Green for success, red for failure
          "Deployment for commit ${{ github.sha }} - $JOB_STATUS"
